ALTER TABLE standings ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'seniori';
ALTER TABLE matches   ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'seniori';
ALTER TABLE players   ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'seniori';
